site:
  title: Local LLM Lab
  start_page: local-llm-lab::index.adoc

content:
  sources:
    - url: ./
      start_path: content

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    source-highlighter: highlightjs

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/summit-2026/ui-bundle.zip
    snapshot: true
